// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhU78fbVIN3zDD1F4qhnvKdpHfrq0Uwyc',
    appId: '1:920814804583:web:d6400986e894db8ce5fec2',
    messagingSenderId: '920814804583',
    projectId: 'movies-b6f66',
    authDomain: 'movies-b6f66.firebaseapp.com',
    storageBucket: 'movies-b6f66.appspot.com',
    measurementId: 'G-4QMGQXSNM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnCZjISHe-dDnlkcy2IkIhaOsBGNXtSs',
    appId: '1:920814804583:android:37688d36cb92eb4de5fec2',
    messagingSenderId: '920814804583',
    projectId: 'movies-b6f66',
    storageBucket: 'movies-b6f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1Igp7wCOZ-raHuu-VylWSX3sSjJRunw',
    appId: '1:920814804583:ios:72ce04cfe1f86eb2e5fec2',
    messagingSenderId: '920814804583',
    projectId: 'movies-b6f66',
    storageBucket: 'movies-b6f66.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS1Igp7wCOZ-raHuu-VylWSX3sSjJRunw',
    appId: '1:920814804583:ios:4f330cd0a678b783e5fec2',
    messagingSenderId: '920814804583',
    projectId: 'movies-b6f66',
    storageBucket: 'movies-b6f66.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
